development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: rails_resume_development
  pool: 5
  username: rails_resume
  password: s0m3th1ng

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: rails_resume_test
  pool: 5
  username: rails_resume
  password: s0m3th1ng
